In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import describe

In [2]:
tips_df = pd.read_csv("tips.csv")
tips_df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
print(tips_df.dtypes)

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object


In [4]:
tips_df = tips_df[['tip', 'total_bill', 'sex', 'smoker', 'time']]

In [5]:
tips_df['sex'] = np.where(tips_df.sex == 'Male', 0, 1)
tips_df['smoker'] = np.where(tips_df.smoker == 'No', 0, 1)
tips_df['time'] = np.where(tips_df.time == 'Dinner', 0, 1)
tips_df.head()

tip  total_bill  sex  smoker  time
0  1.01       16.99    1       0     0
1  1.66       10.34    0       0     0
2  3.50       21.01    0       0     0
3  3.31       23.68    0       0     0
4  3.61       24.59    1       0     0

In [6]:
tips_df.isnull().sum()

tip           0
total_bill    0
sex           0
smoker        0
time          0
dtype: int64

In [7]:
desc_stats = describe(tips_df)

In [8]:
desc_stats.minmax

(array([1.  , 3.07, 0.  , 0.  , 0.  ]),
 array([10.  , 50.81,  1.  ,  1.  ,  1.  ]))

In [9]:
desc_stats.mean

array([ 2.99827869, 19.78594262,  0.35655738,  0.38114754,  0.27868852])

In [10]:
desc_stats.variance

array([ 1.91445464, 79.25293861,  0.23036835,  0.23684477,  0.20184848])

In [11]:
desc_stats.skewness

array([1.45642669, 1.12623463, 0.59894727, 0.48943841, 0.98721777])

In [12]:
desc_stats.kurtosis

array([ 3.54955199,  1.16916813, -1.64126217, -1.76045005, -1.02540107])

In [13]:
X = tips_df[['total_bill','sex', 'smoker', 'time']]
Y = tips_df['tip']

In [14]:
reg = linear_model.LinearRegression().fit(X, Y)

In [15]:
reg.score(X, Y)

0.45943623487583796

In [16]:
reg.coef_

array([ 0.10589995,  0.02904868, -0.14940514, -0.00558348])

In [17]:
reg.intercept_ 

0.9510923659646151